version: '2.3'

services:
  roscore:
    image: ros:noetic
    command: roscore
    expose:
      - 11311
    networks:
      - ros

  carla-sim-mock:
    image: ros:noetic
    command: /integration-tests-startup.sh
    volumes:
      - ./integration-tests-startup.sh:/integration-tests-startup.sh
      - ./recordings:/app/recordings
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: carla-sim-mock
    networks:
      - ros

  local-planner:
    image: local_planner
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: local-planner
    networks:
      - ros

  global-planner:
    image: global_planner
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: global-planner
    networks:
      - ros

  traffic-light-detection:
    image: traffic_light_detection
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: traffic-light-detection
    networks:
      - ros

networks:
  ros:
